version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.data=/tmp/esdata 
    ports:
      - "9200:9200"
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
